# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34e4fc75fb62942c7a67d3080a65a9f46113976eb24a9800e628700f6f3af6b4e2733e7b6862275543a6eb0c3463d1c0abf818e211f06595892647cd87b36f13

test:
  secret_key_base: 8acfe5b8985be6eeb2d63e4eb3b2aa2b3264cde82cf9d09ee8d8068873028caa107dd80d15a7451188476fc47d8bc78bc0ac8c4078cd122e65463b7a80f5cd06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
